name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Check code
      run:  sbt scalafmtCheck test:scalafmtCheck        
    - name: Compile
      run: sbt clean compile
    - name: Test
      run: sbt test it:test      
    - name: Build docker image
      run: sbt docker:publishLocal
